ten = input("nhập tên:")
tuoi = input("nhập tuổi:")
email = input("nhập email")
skype = input("nhập skype:")
dia_chi = input("nhập địa chỉ:")
noi_lam_viec = input("nhập noi lam viec:")
#A)
with open('setinfo.txt','w', encoding='utf-8') as f:
    f.write("Tên: " + ten + "\n")
    f.write("Tuổi: " + tuoi + "\n")
    f.write("Email: " + email + "\n")
    f.write("Skype: " + skype + "\n")
    f.write("Địa chỉ: " + dia_chi + "\n")
    f.write("Nơi làm việc: " + noi_lam_viec + "\n")
print("-> Đã lưu xong vào file setInfo.txt!")
#B)
print("\n--- KẾT QUẢ ĐỌC TỪ FILE ---")
with open('setInfo.txt', 'r', encoding='utf-8') as f:
    print(f.read())